schema: "classroom50/repo-config/v1"
classroom: "cosc2759-2026-semester2"
assignment: "assignment-1"
owner:
  username: "s4073148"
  id: 169015143
  accepted_at: "2026-08-13T05:06:05Z"
source:
  owner: "rmit-computing-technologies"
  owner_id: 82038963
  repo: "cosc2759-2026-assignment-1"
  branch: "main"
