name: Notes Application CI Pipeline

on:
  # Runs on every change on every branch
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
      
jobs:
  lint:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./src

    steps:
      - uses: actions/checkout@v7

      - name: Use Node.js 24.x
        uses: actions/setup-node@v7
        with:
          node-version: "24"

      - name: Install Deps
        run: npm install
        
      - name: Run Lint
        run: |
          mkdir -p logs
          npm run test:lint 2>&1 | tee logs/lint.log

      # Lint artifact
      # Only produce artifact if on main branch
      - if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: lint-${{ github.sha }}
          path: src/logs/lint.log

  unit-test:
    needs: lint
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./src
        
    steps:
      - uses: actions/checkout@v7

      - name: Use Node.js 24.x
        uses: actions/setup-node@v7
        with:
          node-version: "24"

      - name: Install Deps
        run: npm install

      - name: Run Unit Tests
        run: |
          mkdir -p logs/coverage
          npm run test:unit

      # Unit test artifact
      # Only produce artifact if on main branch
      - if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-${{ github.sha }}
          path: src/logs/coverage/