name: Notes Application CI Pipeline

on:
  # Runs on every change on every branch
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  lint:
    #STATIC CODE ANALYSIS/LINT
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./src

    steps:
      - uses: actions/checkout@v7 #Download copy of repo's code to the runner

      - name: Use Node.js 24.x
        uses: actions/setup-node@v7 #Configure Node.js environment to the runner
        with:
          node-version: "24"

      - name: Install Deps
        run: npm install

      - name: Run Lint
        # Make logs directory if it doesn't exist yet
        # Run the lint test script and write it's output on logs/lint.log
        run: |
          mkdir -p logs
          npm run test:lint 2>&1 | tee logs/lint.log

      # Lint artifact
      # Only produce artifact if on main branch
      - if: (success() || failure()) && github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: lint-${{ github.sha }}
          path: src/logs/lint.log

  #UNIT TESTING
  unit-test:
    needs: lint
    if: always() #RUNS REGARDLESS OF ERRORS
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./src

    steps:
      - uses: actions/checkout@v7

      - name: Use Node.js 24.x
        uses: actions/setup-node@v7
        with:
          node-version: "24"

      - name: Install Deps
        run: npm install

      - name: Run Unit Tests
        # Make logs/covreage directory if it doesn't exist yet
        # Run the unit test script. The script already has coverage enabled
        run: |
          mkdir -p logs/coverage/
          npm run test:unit

      # Unit test artifact
      # Only produce artifact if on main branch
      - if: (success() || failure()) && github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-${{ github.sha }}
          path: src/logs/coverage/

  e2e-test:
    needs: unit-test
    if: always() #RUNS REGARDLESS OF ERRORS
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./src

    # Use MongoDB
    services:
      mongodb:
        image: mongo:8.3.7
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v7

      - name: Use Node.js 24.x
        uses: actions/setup-node@v7
        with:
          node-version: "24"

      - name: Install Deps
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright@1.20.0 install

      - name: Run Playwright tests
        run: npm run test:e2e

      - if: (success() || failure()) && github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: e2e-test-${{ github.sha }}
          path: src/playwright-report

  build:
    # Only make build if:
    # 1. All tests are passed
    # 2. Change is on the main branch
    needs: [lint, unit-test]
    if: success() && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./

    steps:
      - uses: actions/checkout@v7

      - name: Use Node.js 24.x
        uses: actions/setup-node@v7
        with:
          node-version: "24"

      - name: Install Deps
        run: |
          cd src
          npm install

      - name: Make Deployable
        run: |
          mkdir -p deployable-${{ github.sha }}
          cp -R src/. deployable-${{ github.sha }}/

      - name: Upload Deployable Artifact
        uses: actions/upload-artifact@v4
        with:
          name: deployable-${{ github.sha }}
          path: deployable-${{ github.sha }}/
